CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    email varchar NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT unique_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar NOT NULL,
    requestor_id bigint REFERENCES users (id),
    created_date timestamp NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    description varchar NOT NULL,
    is_available boolean NOT NULL,
    owner_id bigint REFERENCES users (id) ON DELETE CASCADE,
    request_id bigint REFERENCES requests (id) ON DELETE CASCADE,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar NOT NULL,
    item_id bigint REFERENCES items (id) ON DELETE CASCADE,
    author_id bigint REFERENCES users (id) ON DELETE CASCADE,
    created timestamp NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    item_id bigint REFERENCES items (id) ON DELETE CASCADE,
    booker_id bigint REFERENCES users (id) ON DELETE CASCADE,
    status varchar NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);
